### ISSUE TITLE
Modifying RUN_uncor.m to use glider model

### ISSUE THREAD

**Issue by Wh0DKnee** [Airspace-Encounter-Models/em-model-manned-bayes#27]
Hi,

I'm trying to modify RUN_uncor to generate tracks using the "glider_v1p2.txt" instead of "uncor_1200exclude_fwse_v1p2.txt". I've set the parameters_filename to point to the "glider_v1p2.txt". 

I've adjusted the start distribution to be initialized to cell(5,1) and I've set start{1} (the altitude layer) to 2. From my understanding, all other variables of the start distribution are only dependent on the altitude layer and don't need to be specified. When I try to run the program, I get the following error:
![glider](https://user-images.githubusercontent.com/20592313/144834587-84dd91b3-fb20-4291-aa41-1d81d482a111.jpg)

Here's the complete file (changed the file extension to .txt just so I can upload it here):
[RUN_uncor.m.txt](https://github.com/Airspace-Encounter-Models/em-model-manned-bayes/files/7660172/RUN_uncor.m.txt)

What am I missing?

Thanks!

**Comment by aweinert-MIT** [comment]
The glider model has a different Bayesian network structure as the uncorrelated conventional aircraft models. I suspect this is the root cause of the bug. We have adding glider model support as a task on the [roadmap](https://airspace-encounter-models.github.io/Roadmap/). 

P.S. The encounter model team was on holiday for a good chunk of December and January, hence the delay in addressing this issue.

**Comment by aweinert-MIT** [comment]
Please switch to the dev-unconv branch and confirm that the issue has been resolved. This bug occurred when a dynamic variable in the transition network was dependent on another dynamic variable. There were a few other bugs I resolved too and linked to pull request #33 

Commit 73c2e83bfdd075035ff4c138d5c1a70f559605eb updates `dbn_sample` to use previous implementation if a dynamic variable depends on another dynamic variable. In release 1.4.0 `dbn_sample` was updated to calculate the index, `j`, upfront because `asub2ind` can introduce unwanted overhead and also preallocated events as a NaN array. In this previous release, the `for ii = order_transition` loop was added to identify the relationship between dynamic variables and its parents. Notably in the for `ii = order_transition` loop, the variable `x` was not updated. Now this is where the bug was introduced.

If a dynamic variable was dependent on another dynamic variable (see unconventional glider model), `xj = x(parents)` would be equal for the element with the dynamic variable dependence. This would results in `asub2ind(rj, xj)` returning a negative value, which would create an error when indexing `N_transition{ii}(:, j(ii))`.

Since the uncorrelated conventional models transition networks do not have any dynamic variables not dependent on another dynamic variable, this bug was not identified in release [1.4.0]. Note in this figure from ATC-404 that none of the (t+1) are connected
![uncor conventional aircraft transition network](https://user-images.githubusercontent.com/38636942/151482538-b4042540-8986-49e5-92b1-fcdc91e0f80d.png)

However in the glider transition network from ATC-348, observe that psi dot (t+1) and v dot (t+1) are dependent upon h dot (t+1).  The bug would occur sampling psi dot (t+1) because the element in `x` corresponding to h dot (t+1) would be `0`, which would result in `asub2ind(rj, xj)` returning a negative value. This element was `0` due to preallocating `x = [initial zeros(1, numel(dynamic_variables))];`

![image](https://user-images.githubusercontent.com/38636942/151482661-243be0d9-ae24-44db-9bb3-eac9b270d262.png)

The bug was addressed by determining if any of the dynamic variables depend on another dynamic variable. This determines if we can calculate the index, `j`, upfront or via each iterate of `t`. If there is a dependence, it will sample the model similar to Release [1.3.0] where the events matrix was also preallocated as an empty array

**Comment by Wh0DKnee** [comment]
That resolved the issue, thank you very much for the fix and the thorough explanation!
